import { and, desc, eq } from "drizzle-orm";
import { getDb } from "@/db";
import { agents, auditEvents, bounties, evidence, mandates, missions, taskPlans, users } from "@/db/schema";
import { getChatGPTUser } from "@/app/chatgpt-auth";
import { composePlan, protocolSnapshot } from "@/lib/bnb-agent";

const fail=(error:string,status=400)=>Response.json({error},{status});
async function currentUser(){const user=await getChatGPTUser();if(!user)return null;const db=getDb();await db.insert(users).values({id:user.id,email:user.email,displayName:user.displayName}).onConflictDoUpdate({target:users.id,set:{email:user.email,displayName:user.displayName}});return user}

export async function GET(){try{const user=await currentUser();if(!user)return fail("Authentication required",401);const db=getDb();const [agentRows,bountyRows,missionRows,mandateRows]=await Promise.all([db.select().from(agents).where(eq(agents.ownerId,user.id)).orderBy(desc(agents.createdAt)).limit(50),db.select().from(bounties).where(eq(bounties.ownerId,user.id)).orderBy(desc(bounties.createdAt)).limit(50),db.select().from(missions).where(eq(missions.ownerId,user.id)).orderBy(desc(missions.createdAt)).limit(50),db.select().from(mandates).where(eq(mandates.ownerId,user.id)).orderBy(desc(mandates.createdAt)).limit(20)]);return Response.json({user,agents:agentRows.map(a=>({...a,skills:JSON.parse(a.skillsJson)})),bounties:bountyRows.map(b=>({...b,skills:JSON.parse(b.skillsJson)})),missions:missionRows,mandates:mandateRows})}catch(error){return fail(error instanceof Error?error.message:"Unexpected error",500)}}

export async function POST(request:Request){try{const user=await currentUser();if(!user)return fail("Authentication required",401);const body=await request.json() as Record<string,unknown>;const action=String(body.action||"");const db=getDb();
  if(action==="create_bounty"){const title=String(body.title||"").trim(),acceptance=String(body.acceptanceCriteria||"").trim(),reward=Math.round(Number(body.rewardAmount||0));if(!title||!acceptance||reward<1)return fail("Title, acceptance criteria and a positive reward are required");const publicCode=`B-${Date.now().toString().slice(-6)}`;const[row]=await db.insert(bounties).values({ownerId:user.id,publicCode,title,sponsor:user.displayName,rewardAmount:reward,rewardAsset:String(body.rewardAsset||"USDT"),difficulty:String(body.difficulty||"EXPERT"),acceptanceCriteria:acceptance,skillsJson:JSON.stringify(body.skills||[]),deadlineAt:new Date(Date.now()+72*60*60*1000)}).returning();await db.insert(auditEvents).values({actorId:user.id,entityType:"bounty",entityId:String(row.id),action:"created",payloadJson:JSON.stringify({publicCode,reward})});return Response.json({bounty:{...row,skills:JSON.parse(row.skillsJson)}},{status:201})}
  if(action==="create_agent"){const name=String(body.name||"").trim().toUpperCase(),role=String(body.role||"").trim();if(!name||!role)return fail("Name and role are required");const code=`AGENT-${Date.now().toString().slice(-5)}`;const[row]=await db.insert(agents).values({ownerId:user.id,name,code,role,skillsJson:JSON.stringify(body.skills||[]),color:String(body.color||"cyan")}).returning();await db.insert(auditEvents).values({actorId:user.id,entityType:"agent",entityId:String(row.id),action:"published",payloadJson:JSON.stringify({code})});return Response.json({agent:{...row,skills:JSON.parse(row.skillsJson)}},{status:201})}
  if(action==="deploy_mission"){const name=String(body.name||"Agent squad mission").trim(),intent=String(body.intent||name).trim();const plan=composePlan(intent),publicCode=`M-${Date.now().toString().slice(-6)}`;const[row]=await db.insert(missions).values({ownerId:user.id,publicCode,name,phase:"Execution",status:"ACTIVE",progress:5,payoutAmount:plan.risk.maxBudget}).returning();const[mandate]=await db.insert(mandates).values({ownerId:user.id,missionId:row.id,name:`${name} mandate`,actionsJson:JSON.stringify(plan.risk.actions),budgetAmount:plan.risk.maxBudget,expiresAt:new Date(Date.now()+plan.risk.expiresHours*60*60*1000)}).returning();const[taskPlan]=await db.insert(taskPlans).values({ownerId:user.id,missionId:row.id,intent,stepsJson:JSON.stringify(plan.steps),squadJson:JSON.stringify(plan.squad),riskJson:JSON.stringify(plan.risk)}).returning();await db.insert(evidence).values({ownerId:user.id,missionId:row.id,kind:"acceptance-criteria",uri:`binanceff://mission/${publicCode}/criteria`,digest:`pending:${publicCode}`});await db.insert(auditEvents).values({actorId:user.id,entityType:"mission",entityId:String(row.id),action:"deployed",payloadJson:JSON.stringify({publicCode,mandateId:mandate.id,taskPlanId:taskPlan.id,protocol:protocolSnapshot()})});return Response.json({mission:row,mandate,plan:{...plan,id:taskPlan.id},protocol:protocolSnapshot()},{status:201})}
  if(action==="revoke_mandate"){const id=Number(body.id);if(!id)return fail("Mandate id is required");const[row]=await db.update(mandates).set({revokedAt:new Date()}).where(and(eq(mandates.id,id),eq(mandates.ownerId,user.id))).returning();if(!row)return fail("Mandate not found",404);await db.insert(auditEvents).values({actorId:user.id,entityType:"mandate",entityId:String(id),action:"revoked"});return Response.json({mandate:row})}
  return fail("Unsupported action");}catch(error){return fail(error instanceof Error?error.message:"Unexpected error",500)}}
