export {
  CHAINS,
  DEFAULT_NOTIONAL_USD,
  DEFAULT_SLIPPAGE_BPS,
  MICRO,
  OPPORTUNITY_TTL_MS,
  PAIRS,
  QUOTE_TTL_MS,
  RADAR_MODE,
  RADAR_SOURCE,
  VENUES,
  assessRisk,
  catalog,
  chainById,
  computeNet,
  isStale,
  microToUsd,
  scanChain,
  scanFromBooks,
  simulateOpportunity,
  usdToMicro,
  venuesFor,
} from "./radar-math.mjs";
export type { RadarOpportunity, RadarRisk, RadarSimulation } from "./radar-math.mjs";
